# 
# /*
#  * *********** WARNING **************
#  * This file generated by Apache2::Build/0.01
#  * Any changes made here will be lost
#  * ***********************************
#  * 01: lib/ModPerl/Code.pm:708
#  * 02: lib/Apache2/Build.pm:924
#  * 03: lib/Apache2/Build.pm:944
#  * 04: Makefile.PL:313
#  * 05: Makefile.PL:56
#  */
# 
package Apache2::BuildConfig;

use Apache2::Build ();

sub new {
    bless( {
        'API_VERSION' => 2,
        'APXS_APR_BINDIR' => '/usr/bin',
        'APXS_BINDIR' => '/usr/bin',
        'APXS_INCLUDEDIR' => '/usr/include/apache2',
        'MP_APR_LIB' => 'aprext',
        'MP_APXS' => '/usr/bin/apxs2',
        'MP_CCOPTS' => '-g -Wall',
        'MP_COMPAT_1X' => 1,
        'MP_GENERATE_XS' => 1,
        'MP_INCLUDE_DIR' => '/usr/include/apache2 /usr/include/apr-0',
        'MP_LIBNAME' => 'mod_perl',
        'MP_TRACE' => '0',
        'MP_USE_DSO' => '1',
        'MP_USE_GTOP' => '1',
        'MP_USE_STATIC' => '0',
        'VERSION' => '2.0.2',
        'ap_includedir' => '/usr/include/apache2',
        'apr_bindir' => '/usr/bin',
        'apr_config' => {
                          'HAS_DSO' => '1',
                          'HAS_FORK' => '1',
                          'HAS_INLINE' => '1',
                          'HAS_LARGE_FILES' => '0',
                          'HAS_MMAP' => '1',
                          'HAS_RANDOM' => '1',
                          'HAS_SENDFILE' => '1',
                          'HAS_THREADS' => '1'
                        },
        'apr_config_path' => '/usr/bin/apr-config',
        'apr_includedir' => '/usr/include/apr-0',
        'cwd' => '/mod_perl-2.0.2',
        'dir' => undef,
        'file_build_config' => 'lib/Apache2/BuildConfig.pm',
        'file_ldopts' => 'src/modules/perl/ldopts',
        'file_makefile' => 'src/modules/perl/Makefile',
        'httpd_is_source_tree' => '',
        'httpd_version' => {
                             '/usr/include/apache2' => '2.0.55'
                           },
        'libpth' => [
                      '/usr/local/lib',
                      '/lib',
                      '/usr/lib'
                    ]
      }, 'Apache2::Build' );
}

1;
