language: perl
before_install:
    - sudo apt-add-repository -y ppa:rsrchboy/ndn-perl
    - sudo apt-get update -q
install:
    - sudo apt-get install -y -q build-essential debhelper devscripts equivs pristine-tar
    - sudo mk-build-deps --install debian/control
    - BRANCH=`git symbolic-ref --short HEAD` ; git checkout pristine-tar ; git checkout $BRANCH
    - pristine-tar checkout libapache2-mod-perl2_2.0.9~1624218.orig.tar.xz
script:
    - debuild -S -us -uc --lintian-opts --profile ndn
    - debuild -us -uc --lintian-opts --profile ndn
    - sudo dpkg -i ../*.deb
