Document: ndn-perl-apache2-mod-perl
Title: Debian ndn-perl-apache2-mod-perl Manual
Author: <insert document author here>
Abstract: This manual describes what ndn-perl-apache2-mod-perl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ndn-perl-apache2-mod-perl/ndn-perl-apache2-mod-perl.sgml.gz

Format: postscript
Files: /usr/share/doc/ndn-perl-apache2-mod-perl/ndn-perl-apache2-mod-perl.ps.gz

Format: text
Files: /usr/share/doc/ndn-perl-apache2-mod-perl/ndn-perl-apache2-mod-perl.text.gz

Format: HTML
Index: /usr/share/doc/ndn-perl-apache2-mod-perl/html/index.html
Files: /usr/share/doc/ndn-perl-apache2-mod-perl/html/*.html
